.TH stiv "1" "March 2020"
.SH NAME
stiv \- image previews on the terminal using ueberzug.
.SH SYNOPSIS
.B stiv
\fI\,FILE WIDTH HEIGHT\/\fR [\fI\,X Y\/\fR]
.br
.B stiv
\fI\,\-c | \-\-clear [ 0 | 1 ]\/\fR
.br
.B stiv
\fI\,\-h | \-\-help\/\fR
.br
.SH DESCRIPTION
.\" Add any additional description here
.PP
In the 1st form, draw FILE with maximum WIDTH and HEIGHt on position (X, Y).
.PP
In the 2nd form, clear previous draws.
.PP
In the 3rd form, print help message.
.PP
Mandatory arguments to long options are mandatory for short options too.
.TP
\fB\-\-help\fR
display this help and exit
.TP
\fB\-\-clear WHICH\fR
Clear previous draws. If WHICH is 1, clear previews. Else, clear others.
.SH AUTHOR
Written by Lucas Mior.
.SH COPYRIGHT
Copyright \(co 2020 Lucas Mior.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
.SH "SEE ALSO"
link(2), symlink(2)
